@startuml QMP2

class Prenda {
  tipo : TipoDePrenda
  material : Material
  colorPrincipal : Color
  colorSecundario : Color
  trama : Trama

  Categoria getCategoria()
}


class Color {
  rojo : int
  verde : int
  azul : int 
}

enum Categoria {
  CALZADO,
  PARTE_SUPERIOR,
  PARTE_INFERIOR,
  ACCESORIO,
}

enum Material {
  ALGODON,
  LINO,
  LANA,
  POLIESTER,
  SEDA,
}

class TipoDePrenda {
  categoria : Categoria  
  
  Categoria getCategoria()
}

Prenda --> Material
Prenda --> TipoDePrenda
Prenda --> Color
TipoDePrenda --> Categoria
' Prenda conoce su Material
' Prenda --> "1" Categoria


enum Trama{
  LISA,
  RAYADA,
  CON_LUNARES,
  A_CUADROS,
  ESTAMPADO,
}

' Trama corresponde a la tela, eso quiere decir que
' corresponde al Material? De ser asi debemos agregarle comportamiento
' al enum de Material creo
' IMO: Hay que agregarlo directamente a la prenda como propiedad
Prenda --> Trama

' El borrador deberia ser una clase "parecida" a la Prenda, e
' incluso dentro de su constructor, podemos hacer las validaciones
' de los datos para crear a la prenda desde alli

class Borrador {
  tipo : TipoDePrenda
  material : Material
  colorPrincipal : Color
  colorSecundario : Color
  trama : Trama

  void cargarMaterial(material)
  void cargarColorPrincipal(colorPrincipal)
  void cargarColorSecundario(colorSecundario)
  void cargarTrama(trama)
  Prenda crearPrenda()
}

class Uniforme {
  parteSuperior : Prenda
  parteInferior : Prenda
  calzado : Prenda
}

Uniforme -->"3" Prenda
Borrador ..> Prenda

@enduml
