@startuml QMP1

class Prenda {
  tipo : string
  material : string
  colorPrincipal : string
  colorSecundario : string
}

class Categoria {
  tiposValidos: List<string>
  bool  esTipoCorrespondienteACategoria()
}

Prenda --> "1" Categoria

class Atuendo

Atuendo --> "*" Prenda
@enduml
